### ISSUE TITLE
Slack notification channel

### ISSUE THREAD

**Issue by itsderek23** [scoutapp/roadmap#13]
Add a Slack notification channel for alerts.

**Comment by cookandy** [comment]
Any update on this one please? Slack integration would be really useful.

**Comment by ibrahima** [comment]
This would be very helpful! In the meantime, you can use https://get.slack.help/hc/en-us/articles/206819278-Send-emails-to-Slack to send email notifications to a Slack channel.

**Comment by danielkandel** [comment]
It would definitely be great to have this.

**Comment by neilvcarvalho** [comment]
That would be great! I receive alerts on my e-mail, but I try to see my e-mails a few times a day. Slack is syncronous and my colleagues and I can discuss the alert.

**Comment by dlanderson** [comment]
We have released Webhook notification channels. These can be combined with [Zapier](https://zapier.com/) (free to use) in order to receive APM alerts in Slack.

**Comment by matthewchigira** [comment]
Alert Notifications with Slack
======================


To integrate Slack with Scout's Alert Notification system, you can utilize the Webhook feature on the *Application > Notification Channels* page.

In order for Scout and Slack to be able to work together, you need to use a third-party service called [Zapier](https://zapier.com/).

Zapier is a service which allows you to connect different web services together to make custom work-flows.

## Zapier Configuration

First of all you will need to create an account with [Zapier](https://zapier.com/), and once you have done this, you can go ahead and create a *Zap*, by clicking on the Make a Zap! button on the top right-hand side of the screen, as shown in the image below.

![1](https://user-images.githubusercontent.com/43639290/55203245-2b3dc900-520e-11e9-8564-8187721bcbeb.png "Creating a new Zap")

You need to create a *Trigger* (for Scout) and an *Action* (for Slack) in order to make the two systems able to communicate. First of all, create the trigger by selecting *Webhooks by Zapier* as the App you want to work with.

![2](https://user-images.githubusercontent.com/43639290/55203246-2b3dc900-520e-11e9-8584-13b4e492607a.png "Create a Scout trigger")

Next you will need to select the type of trigger that you want, select *Catch Hook*. Next you will be given a URL, which is the Webhook that we will use to link to in Scout. Copy this URL and then open up Scout.

![3](https://user-images.githubusercontent.com/43639290/55203247-2bd65f80-520e-11e9-8032-466ea326848f.png "Copy the Webhook URL")

## Scout Configuration

In Scout, navigate to *Application > Notification Channels* and create a new Webhook, like the picture below, copying in the Zapier URL.

![4](https://user-images.githubusercontent.com/43639290/55203248-2bd65f80-520e-11e9-94df-53d5ee67e68a.png "Create a Notification Channel")

Next you will need to add or edit a Notification Group to include this new channel.

![5](https://user-images.githubusercontent.com/43639290/55203249-2c6ef600-520e-11e9-81fa-9f62250b97da.png "Create/Edit Notification Group")

## Create an Alert

At this point if you try to carry on creating the Zap in Zapier, it will try to pull a sample Alert from Scout using the Webhook that we set up. The reason it does this is that it requires sample data from Scout in order to understand the format of the trigger, and what fields are available from the Scout. However, at this point there are not going to be any Alerts it can use because this Webhook has only just been set up. So here you have two options:

* Create a quick Alert in Scout to generate this sample data.
* Click *Skip This Step* and then *Continue Without Samples*.

We **strongly recommend** the first option, because later on when you are specifying the message that you are going to send to Slack, if you do not have sample data, you will not be able to use data that came from Scout. 

![6](https://user-images.githubusercontent.com/43639290/55203251-2c6ef600-520e-11e9-85b7-659a97126132.png "Pick a sample Alert")

To create a quick Alert, open up Scout, go to *Alert > Alert Conditions* and create a simple condition that will alert, and choose the Slack Notification Group we set up earlier.

![7](https://user-images.githubusercontent.com/43639290/55203252-2d078c80-520e-11e9-8161-5d63a451b82a.png "Create Alert Condition")

## Choose the Alert in Zapier

After the Alert has occurred in Scout, go back to Zapier and click the *Ok, I did this* button and it will connect with Scout and look for an Alert with this matching Webhook. Choose this as the sample you want to use and click *Continue*.

![8](https://user-images.githubusercontent.com/43639290/55203253-2d078c80-520e-11e9-97ab-a405b934cd47.png "Pick a sample Alert")

## Create a Slack Action

Next you need to add an Action step to the work-flow, this is the part were we integrate Slack. Click *Add a Step* on the left-hand side of the page.

![9](https://user-images.githubusercontent.com/43639290/55203254-2d078c80-520e-11e9-8082-7d3d1f00301b.png "Add a Step")

Next click the *Action/Search* option, and you will be given the option to choose an app to connect.

![10](https://user-images.githubusercontent.com/43639290/55203255-2da02300-520e-11e9-90b0-690948be9e93.png "Add an Action/Search")

Choose Slack, and then a new Action will be created on the left-hand side of the screen.

![11](https://user-images.githubusercontent.com/43639290/55203256-2da02300-520e-11e9-9b60-69e38ab5ed85.png "Choose an App")

There are many different types of Slack Action that you can choose to perform, but let's choose *Send Channel Message*.

![12](https://user-images.githubusercontent.com/43639290/55203258-2e38b980-520e-11e9-9b16-8196b7d7a322.png "Select a Slack Action")

Next you can configure many aspects of the message that will be sent, such as which channel to send the message to and what particular data comes from the Scout Alert (shown in green). It is only possible to pull this data from Scout here if you created an Alert earlier like we advised.

![13](https://user-images.githubusercontent.com/43639290/55203260-2e38b980-520e-11e9-80ff-f82ee4d37747.png "Configure the Message")

Then you can send a test message to Slack to preview how it will look.

![14](https://user-images.githubusercontent.com/43639290/55203262-2ed15000-520e-11e9-9403-c88481952deb.png "Test Slack")

Then all that's left to do is to give your Zap a descriptive name and enable it.

![15](https://user-images.githubusercontent.com/43639290/55203264-2ed15000-520e-11e9-8278-f11f6f414990.png "Give your zap a name")

Now everything is set up so that whenever an Alert occurs in Scout which is linked to this Notification Channel, you will see a message in Slack.

![16](https://user-images.githubusercontent.com/43639290/55203265-2ed15000-520e-11e9-9f36-649455f9318b.png "The end result")
