### ISSUE TITLE
PagerDuty Integration

### ISSUE THREAD

**Issue by itsderek23** [scoutapp/roadmap#15]
Ability to send alerts to PagerDuty

**Comment by danbt79** [comment]
👍

**Comment by dlanderson** [comment]
We have released Webhook notification channels. These can be combined with Zapier (free to use) in order to receive APM alerts in PagerDuty.

**Comment by matthewchigira** [comment]
Alert Notifications with PagerDuty
==========================


To integrate PagerDuty with Scout's Alert Notification system, you can utilize the Webhook feature on the *Application > Notification Channels* page.

In order for Scout and PagerDuty to be able to work together, you need to use a third-party service called [Zapier](https://zapier.com/).

Zapier is a service which allows you to connect different web services together to make custom work-flows.

## Zapier Configuration

First of all you will need to create an account with [Zapier](https://zapier.com/), and once you have done this, you can go ahead and create a *Zap*, by clicking on the Make a Zap! button on the top right-hand side of the screen, as shown in the image below.

![1](https://user-images.githubusercontent.com/43639290/55204119-3f36fa00-5211-11e9-9d53-4257f114493a.png "Creating a new Zap")

You need to create a *Trigger* (for Scout) and an *Action* (for PagerDuty) in order to make the two systems able to communicate. First of all, create the trigger by selecting *Webhooks by Zapier* as the App you want to work with.

![2](https://user-images.githubusercontent.com/43639290/55204120-3fcf9080-5211-11e9-8fc6-60b2d438daad.png "Create a Scout trigger")

Next you will need to select the type of trigger that you want, select *Catch Hook*. Next you will be given a URL, which is the Webhook that we will use to link to in Scout. Copy this URL and then open up Scout.

![3](https://user-images.githubusercontent.com/43639290/55204121-3fcf9080-5211-11e9-9a1c-f997a6b2b221.png "Copy the Webhook URL")

## Scout Configuration

In Scout, navigate to *Application > Notification Channels* and create a new Webhook, like the picture below, copying in the Zapier URL.

![4](https://user-images.githubusercontent.com/43639290/55204122-3fcf9080-5211-11e9-8e09-72868dee47b9.png "Create a Notification Channel")

Next you will need to add or edit a Notification Group to include this new channel.

![5](https://user-images.githubusercontent.com/43639290/55204123-40682700-5211-11e9-84c6-3ec7333332c1.png "Create/Edit Notification Group")

## Create an Alert

At this point if you try to carry on creating the Zap in Zapier, it will try to pull a sample Alert from Scout using the Webhook that we set up. The reason it does this is that it requires sample data from Scout in order to understand the format of the trigger, and what fields are available from the Scout. However, at this point there are not going to be any Alerts it can use because this Webhook has only just been set up. So here you have two options:

* Create a quick Alert in Scout to generate this sample data.
* Click *Skip This Step* and then *Continue Without Samples*.

We **strongly recommend** the first option, because later on when you are specifying the message that you are going to send to PagerDuty, if you do not have sample data, you will not be able to use data that came from Scout. 

![6](https://user-images.githubusercontent.com/43639290/55204126-40682700-5211-11e9-8894-35d22887b8d0.png "Pick a sample Alert")

Open up Scout, go to *Alert > Alert Conditions* and create a simple condition that will alert, and choose the PagerDuty Notification Group we set up earlier.

![7](https://user-images.githubusercontent.com/43639290/55204128-4100bd80-5211-11e9-8a2e-0680cab2a0b8.png "Create Alert Condition")

## Choose the Alert in Zapier

After the Alert has occurred in Scout, go back to Zapier and click the *Ok, I did this* button and it will connect with Scout and look for an Alert with this matching Webhook. Choose this as the sample you want to use and click *Continue*.

![8](https://user-images.githubusercontent.com/43639290/55204129-4100bd80-5211-11e9-9b56-7137e7068be8.png "Pick a sample Alert")

## Create a PagerDuty Action

Next you need to add an Action step to the work-flow, this is the part were we integrate PagerDuty. Click *Add a Step* on the left-hand side of the page.

![9](https://user-images.githubusercontent.com/43639290/55204130-4100bd80-5211-11e9-940d-e67868452fba.png "Add a Step")

Next click the *Action/Search* option, and you will be given the option to choose an app to connect.

![10](https://user-images.githubusercontent.com/43639290/55204131-41995400-5211-11e9-8891-ae3e6f427b2a.png "Add an Action/Search")

Choose PagerDuty, and then a new Action will be created on the left-hand side of the screen.

![11](https://user-images.githubusercontent.com/43639290/55204132-41995400-5211-11e9-8e2b-54b0a3fff48c.png "Choose an App")

## Connect to PagerDuty

After you select the PagerDuty App, you will be asked to connect to your PagerDuty account within Zapier. In order to do this, you will have to open PagerDuty and do some configuration. But before you do that, click the *Connect an Account* button and a pop-up window will appear, do not fill in your details yet but keep the window open as we need it in a moment after we have configured PagerDuty.

![12](https://user-images.githubusercontent.com/43639290/55204134-41995400-5211-11e9-8895-d25503720859.png "Connect a PagerDuty Account")

Once you have opened PagerDuty and logged in, go to *Configuration > API Access*.

![13](https://user-images.githubusercontent.com/43639290/55204136-4231ea80-5211-11e9-8857-2d0e6197b974.png "Add an API Key")

Next click on the green button to create a new API key for Zapier.

![14](https://user-images.githubusercontent.com/43639290/55204137-4231ea80-5211-11e9-9452-0c3291450d09.png) "Add an API Key")

Give the key a descriptive name and then create it and copy it to your clipboard.

![15](https://user-images.githubusercontent.com/43639290/55204138-42ca8100-5211-11e9-9003-b304f8c4ee34.png "Create the Key")

Now go back to the pop-up window from earlier, and type in your PagerDuty Account Name and paste in the generated API Key. After you click the *Yes, Continue* button, your PagerDuty account can be used in Zapier. 

![16](https://user-images.githubusercontent.com/43639290/55204139-42ca8100-5211-11e9-9ab6-c2163e13c828.png "Connect the Key with the Account Name")

## Configure Zapier within PagerDuty

Before going back to Zapier, there is one more thing we need to configure, we need to add Zapier as a Service inside PagerDuty. Go to *Configuration > Services*.

![17](https://user-images.githubusercontent.com/43639290/55204140-42ca8100-5211-11e9-9fef-21d7178fcb48.png "Add a Service")

Then click the green *New Service* button to add the Zapier service to PagerDuty.

![18](https://user-images.githubusercontent.com/43639290/55204141-43631780-5211-11e9-86ff-993bf880d362.png "Add a Service")

Add a Service called Zapier and in the *Integration Type* field, search for the Zapier app. There are many more details that you can customize here.

![19](https://user-images.githubusercontent.com/43639290/55204143-43631780-5211-11e9-97c5-4561cae64bcf.png "Add a Zapier Service")

Once you have added the Service, we now have it set up on both ends, so we can go back to Zapier and finish configuring our Zap.

## Finish configuring Zapier

In Zapier we need to select the type of Action that will occur in PagerDuty when our Scout Alert triggers. There are many different types of PagerDuty Action that you can choose to perform, but let's choose *Add Trigger Event*.

![20](https://user-images.githubusercontent.com/43639290/55204144-43fbae00-5211-11e9-8fa8-eef246152237.png "Select a PagerDuty Action")

Next, you can configure many aspects of the Trigger Event that will be sent. Set the *Integration Key* to "Zapier - Zapier", populate the *Description* field with data from Scout, and include a *Source URL & Name* to provide the user with a link back to the Scout Alert, within the PagerDuty system. It is only possible to pull this data from Scout here if you created an Alert earlier like we advised.

![21](https://user-images.githubusercontent.com/43639290/55204145-43fbae00-5211-11e9-932c-5fb92d685e8e.png "Configure the Trigger Event")

Then all that's left to do is to give your Zap a descriptive name and enable it.

![22](https://user-images.githubusercontent.com/43639290/55204146-43fbae00-5211-11e9-85a9-a598b87a9eef.png "Give your zap a name")

Now everything is set up so that whenever an Alert occurs in Scout which is linked to this Notification Channel, you will see a message in PagerDuty.

![23](https://user-images.githubusercontent.com/43639290/55204147-44944480-5211-11e9-8115-b161730d3e33.png "The end result")
