### ISSUE TITLE
Add a VictorOps notification channel for alerts

### ISSUE THREAD

**Issue by itsderek23** [scoutapp/roadmap#3]

**Comment by dlanderson** [comment]
We have released Webhook notification channels. These can be combined with Zapier (free to use) in order to receive APM alerts in VictorOps.

**Comment by matthewchigira** [comment]
Alert Notifications with VictorOps
=========================


To integrate VictorOps with Scout's Alert Notification system, you can utilize the Webhook feature on the *Application > Notification Channels* page.

In order for Scout and VictorOps to be able to work together, you need to use a third-party service called [Zapier](https://zapier.com/).

Zapier is a service which allows you to connect different web services together to make custom work-flows.

## Zapier Configuration

First of all you will need to create an account with [Zapier](https://zapier.com/), and once you have done this, you can go ahead and create a *Zap*, by clicking on the Make a Zap! button on the top right-hand side of the screen, as shown in the image below.

![1](https://user-images.githubusercontent.com/43639290/55301048-9b01bd00-5475-11e9-9538-2d9e74bb38cc.png "Creating a new Zap")

You need to create a *Trigger* (for Scout) and an *Action* (for VictorOps) in order to make the two systems able to communicate. First of all, create the trigger by selecting *Webhooks by Zapier* as the App you want to work with.

![2](https://user-images.githubusercontent.com/43639290/55301049-9b01bd00-5475-11e9-9c25-75e74a4cd7b7.png "Create a Scout trigger")

Next you will need to select the type of trigger that you want, select *Catch Hook*. Next you will be given a URL, which is the Webhook that we will use to link to in Scout. Copy this URL and then open up Scout.

![3](https://user-images.githubusercontent.com/43639290/55301050-9b9a5380-5475-11e9-91c3-d2923ae78b34.png "Copy the Webhook URL")

## Scout Configuration

In Scout, navigate to *Application > Notification Channels* and create a new Webhook, like the picture below, copying in the Zapier URL.

![4](https://user-images.githubusercontent.com/43639290/55301051-9b9a5380-5475-11e9-9f59-ebb6cfa64f3c.png "Create a Notification Channel")

Next you will need to add or edit a Notification Group to include this new channel.

![5](https://user-images.githubusercontent.com/43639290/55301052-9b9a5380-5475-11e9-9117-fce4c323fa75.png "Create/Edit Notification Group")

## Create an Alert

At this point if you try to carry on creating the Zap in Zapier, it will try to pull a sample Alert from Scout using the Webhook that we set up. The reason it does this is that it requires sample data from Scout in order to understand the format of the trigger, and what fields are available from Scout. However, at this point there are not going to be any Alerts it can use because this Webhook has only just been set up. So here you have two options:

* Create a quick Alert in Scout to generate this sample data.
* Click *Skip This Step* and then *Continue Without Samples*.

We **strongly recommend** the first option, because later on when you are specifying the message that you are going to send to VictorOps, if you do not have sample data, you will not be able to use data that came from Scout. 

![6](https://user-images.githubusercontent.com/43639290/55301054-9c32ea00-5475-11e9-973a-c274fe596ce8.png "Pick a sample Alert")

To create a quick Alert, open up Scout, go to *Alert > Alert Conditions* and create a simple condition that will alert, and choose the VictorOps Notification Group we set up earlier.

![7](https://user-images.githubusercontent.com/43639290/55301055-9c32ea00-5475-11e9-8da5-b4649c00dd71.png "Create Alert Condition")

## Choose the Alert in Zapier

After the Alert has occurred in Scout, go back to Zapier and click the *Ok, I did this* button and it will connect with Scout and look for an Alert with this matching Webhook. Choose this as the sample you want to use and click *Continue*.

![8](https://user-images.githubusercontent.com/43639290/55301056-9ccb8080-5475-11e9-8580-52fe55e18f08.png "Pick a sample Alert")

## Create a VictorOps Action

Next you need to add an Action step to the work-flow, this is the part were we integrate VictorOps. Click *Add a Step* on the left-hand side of the page.

![9](https://user-images.githubusercontent.com/43639290/55301057-9d641700-5475-11e9-8a5d-199463f48cff.png "Add a Step")

Next click the *Action/Search* option, and you will be given the option to choose an app to connect.

![10](https://user-images.githubusercontent.com/43639290/55301058-9d641700-5475-11e9-9119-0f1d0636d5cc.png "Add an Action/Search")

VictorOps does not provide a dedicated App within Zapier, so instead, we will integrate VictorOps using an email service. VictorOps can provide a special email account for each user that will listen for alerts and relay them to the VictorOps system. We will need to do a small amount of configuration in VictorOps, but first in Zapier, choose *Email by Zapier* as the Action App, and then a new Action will be created on the left-hand side of the screen.

![11](https://user-images.githubusercontent.com/43639290/55301059-9dfcad80-5475-11e9-9d91-8536e7f2dfa6.png "Choose an App")

There is only one type of Action that you can choose to perform with Zapier's Email Action, called *Send Channel Message*, so pick this and click continue.

![12](https://user-images.githubusercontent.com/43639290/55301060-9dfcad80-5475-11e9-9893-c0db54ca5f2c.png "Select a VictorOps Action")

## Configure VictorOps

Before we go any further, let's configure VictorOps to expose this special email address to incoming alerts from Zapier. Open up VictorOps and log in, then from the menu at the top of the screen, click on Settings > Alert Behaviour > Integrations. Here you will be presented with a list of Integrations that VictorOps provides. Search for "Email" and open this Integration.

![13](https://user-images.githubusercontent.com/43639290/55301061-9e954400-5475-11e9-846c-6094cd4d786d.png "Search for Email Integration")

Next, click the *Enable Integration* button and VictorOps will generate an email address for you to use.

![14](https://user-images.githubusercontent.com/43639290/55301062-9e954400-5475-11e9-9234-9394ed098283.png "Enable the Integration")

Copy this email address here because we are going to use this in Zapier to integrate VictorOps.

![15](https://user-images.githubusercontent.com/43639290/55301063-9f2dda80-5475-11e9-8ad2-9f6864228865.png "Copy the Email Address")


## Continue Configuring Zapier

That is all the configuration that we need to do in VictorOps, so open Zapier up again and let's continue configuring the Action. The next step is the message configuration. You can configure many aspects of the message that will be sent, such as which email address to use, and the contents of the email. For email address, paste in the the VictorOps email that we copied earlier, but be careful to remove the '+$routing_key' part of the address. Routing Keys allow you to route emails to different sections of VictorOps, but for the purpose of this explanation, we are not going to use them. If you are interested in this feature then please take a look at the [VictorOps documentation](https://help.victorops.com/knowledge-base/victorops-generic-email-endpoint/).

The body field is a good place to choose data that comes from the Scout Alert (shown in green) and pass this information through to VictorOps. It is only possible to pull this data from Scout here if you created an Alert earlier like we advised.

![16](https://user-images.githubusercontent.com/43639290/55301064-9f2dda80-5475-11e9-84dc-a326a5223994.png "Configure the Message")

Then you can send a test message to VictorOps to preview how it will look.

![17](https://user-images.githubusercontent.com/43639290/55301066-9fc67100-5475-11e9-8eca-c199496fd3c1.png "Test VictorOps")

Then all that's left to do is to give your Zap a descriptive name and enable it.

![18](https://user-images.githubusercontent.com/43639290/55301067-9fc67100-5475-11e9-857e-226528401caa.png "Give your zap a name")

Now everything is set up so that whenever an Alert occurs in Scout which is linked to this Notification Channel, you will see a message in VictorOps.

![19](https://user-images.githubusercontent.com/43639290/55301068-a05f0780-5475-11e9-8a51-d264cc1be14a.png "The end result")
