### ISSUE TITLE
30 day timeframe

### ISSUE THREAD

**Issue by wireframe** [scoutapp/roadmap#44]
Hey folks.  I see that we are limited to only the last 7 days of data and we are looking to collect monthly level snapshots to compare performance over time.  Is there a way to enable this or support via URL params?

Current url:
https://apm.scoutapp.com/apps/ID?p=response_time_95th&time=d:7-day

Proposed url:
https://apm.scoutapp.com/apps/ID?p=response_time_95th&time=d:30-day

**Comment by lmansur** [comment]
+1

The main reason I need this is to make better memory growth analysis. The 7-day period is ok for most analysis, but finding memory leaks may require a longer period.

**Comment by itsderek23** [comment]
@lmansur - we're taking a cut at this. 

The challenge is that performance of longer time views varies widely based on the cardinality of the data, and the data we have has a wide spread. 

We need to be more careful on a rollout and may run into unexpected issues that require some workarounds for apps w/higher cardinality data.

Also, just clarifying for others: Scout provides 30 days of data but a maximum time window of 7-days. You can shift the end time father back to view data more than 7 days old.

This issue is to provide a full 30-day view of the data in the UI.

Please 👍 or subscribe to the issue. We'll update as we progress.

**Comment by dlanderson** [comment]
FYI - We support `time=d:30-day` when entered directly in the URL. It is not yet available in the Timeframe dropdown.
