### ISSUE TITLE
xmatters Alerting Channel

### ISSUE THREAD

**Issue by cschneid** [scoutapp/roadmap#75]
A customer has requested we add xmatters as a notification channel.

https://www.xmatters.com/

**Comment by itsderek23** [comment]
API: https://help.xmatters.com/ondemand/xmodwelcome/communicationplanbuilder/appendixrestapi.htm#POSTtrigger

**Comment by dlanderson** [comment]
We have released Webhook notification channels. These can be combined with Zapier (free to use) in order to receive APM alerts in XMatters.

**Comment by matthewchigira** [comment]
Alert Notifications with xMatters
========================


To integrate xMatters with Scout's Alert Notification system, you can utilize the Webhook feature on the *Application > Notification Channels* page.

In order for Scout and xMatters to be able to work together, you need to use a third-party service called [Zapier](https://zapier.com/).

Zapier is a service which allows you to connect different web services together to make custom work-flows.

## Zapier Configuration

First of all you will need to create an account with [Zapier](https://zapier.com/), and once you have done this, you can go ahead and create a *Zap*, by clicking on the Make a Zap! button on the top right-hand side of the screen, as shown in the image below.

![1](https://user-images.githubusercontent.com/43639290/55215012-aff30c00-523b-11e9-87c8-e9d040df0f1c.png "Creating a new Zap")

You need to create a *Trigger* (for Scout) and an *Action* (for xMatters) in order to make the two systems able to communicate. First of all, create the trigger by selecting *Webhooks by Zapier* as the App you want to work with.

![2](https://user-images.githubusercontent.com/43639290/55215013-b08ba280-523b-11e9-846b-aca5822db609.png "Create a Scout trigger")

Next you will need to select the type of trigger that you want, select *Catch Hook*. Next you will be given a URL, which is the Webhook that we will use to link to in Scout. Copy this URL and then open up Scout.

![3](https://user-images.githubusercontent.com/43639290/55215014-b08ba280-523b-11e9-9976-a03fbf5e2559.png "Copy the Webhook URL")

## Scout Configuration

In Scout, navigate to *Application > Notification Channels* and create a new Webhook, like the picture below, copying in the Zapier URL.

![4](https://user-images.githubusercontent.com/43639290/55215015-b08ba280-523b-11e9-9c61-999aba2808d9.png "Create a Notification Channel")

Next you will need to add or edit a Notification Group to include this new channel.

![5](https://user-images.githubusercontent.com/43639290/55215017-b1243900-523b-11e9-8d78-437f04e0811d.png "Create/Edit Notification Group")

## Create an Alert

At this point if you try to carry on creating the Zap in Zapier, it will try to pull a sample Alert from Scout using the Webhook that we set up. The reason it does this is that it requires sample data from Scout in order to understand the format of the trigger, and what fields are available from the Scout. However, at this point there are not going to be any Alerts it can use because this Webhook has only just been set up. So here you have two options:

* Create a quick Alert in Scout to generate this sample data.
* Click *Skip This Step* and then *Continue Without Samples*.

We **strongly recommend** the first option, because later on when you are specifying the message that you are going to send to xMatters, if you do not have sample data, you will not be able to use data that came from Scout. 

![6](https://user-images.githubusercontent.com/43639290/55215018-b1243900-523b-11e9-8dd5-4d570340d981.png "Pick a sample Alert")

Open up Scout, go to *Alert > Alert Conditions* and create a simple condition that will alert, and choose the xMatters Notification Group we set up earlier.

![7](https://user-images.githubusercontent.com/43639290/55215019-b1bccf80-523b-11e9-8ddc-2dbade64ac74.png "Create Alert Condition")

## Choose the Alert in Zapier

After the Alert has occurred in Scout, go back to Zapier and click the *Ok, I did this* button and it will connect with Scout and look for an Alert with this matching Webhook. Choose this as the sample you want to use and click *Continue*.

![8](https://user-images.githubusercontent.com/43639290/55215020-b1bccf80-523b-11e9-851b-ed5c0ff5647b.png "Pick a sample Alert")

## Create a xMatters Action

Next you need to add an Action step to the work-flow, this is the part were we integrate xMatters. Click *Add a Step* on the left-hand side of the page.

![9](https://user-images.githubusercontent.com/43639290/55215022-b1bccf80-523b-11e9-879d-b0d01922f86b.png "Add a Step")

Next click the *Action/Search* option, and you will be given the option to choose an app to connect.

![10](https://user-images.githubusercontent.com/43639290/55215023-b2556600-523b-11e9-8c71-57ba99090d44.png "Add an Action/Search")

Choose xMatters, and then a new Action will be created on the left-hand side of the screen.

![11](https://user-images.githubusercontent.com/43639290/55215024-b2556600-523b-11e9-9609-cb2a429f7fc0.png "Choose an App")

## Connect to xMatters

After you select the xMatters App, you will be asked to connect to your xMatters account within Zapier. In order to do this, you will have to open xMatters and do some configuration. But before you do that, click the *Connect an Account* button and a pop-up window will appear, do not fill in your details yet but keep the window open as we need it in a moment after we have configured xMatters.

![12](https://user-images.githubusercontent.com/43639290/55215025-b2edfc80-523b-11e9-9854-e77efcb20854.png "Connect a xMatters Account")

Once you have opened xMatters and logged in, go to *USERS* on the top menu, and then click on the Integration User, this is the account that we are going to use to connect Zapier with xMatters.

![13](https://user-images.githubusercontent.com/43639290/55215026-b2edfc80-523b-11e9-860f-df5671989142.png "Configure User")

On the Integration User screen click on the *Change Login* button so that you can give this user a password. Also make sure that you make a note of the Web Login field for this user.

![14](https://user-images.githubusercontent.com/43639290/55215027-b2edfc80-523b-11e9-9ab4-428640bc2930.png "Change Login Details")

Next we will need to give this user permission to be able to send a message. To do this click on *ROLES* and add the *Full Access User* Role and then click *Save*. This will grant access to the *Send Messages* function which is required.

![15](https://user-images.githubusercontent.com/43639290/55215028-b3869300-523b-11e9-96c3-b41260ae9916.png "Grant Permissions")

Now go back to the pop-up window from earlier, and type the Web Login (which just noted down) into the Username box and type in the password we set up and your xMatters host name. After you click the *Yes, Continue* button, your xMatters account can be used in Zapier. 

![16](https://user-images.githubusercontent.com/43639290/55215029-b3869300-523b-11e9-924a-392e7c214d38.png "Connect xMatters Account to Zapier")

Now is a good time to test if this worked before moving on.

![17](https://user-images.githubusercontent.com/43639290/55215030-b41f2980-523b-11e9-9b14-20d5169e1dfe.png "Add a Service")


## Configure xMatters

Before carrying on in Zapier, there is one more thing we need to do in xMatters. Click on the *DEVELOPER* link on the main screen and then click the green *Edit* button of the Communication Plan that you want to use, and then click *Forms*.

![18](https://user-images.githubusercontent.com/43639290/55215031-b41f2980-523b-11e9-9259-6a913e7beb84.png "Edit a Communication Plan")

On the *Send Alert* form, click the drop down box and choose *Access Web Service URL*, and copy the URL that appears on the screen. We are going to use this in Zapier next.

![19](https://user-images.githubusercontent.com/43639290/55215033-b4b7c000-523b-11e9-8b1d-c4e01d31d4b9.png "Obtain the Send Alert Service URL")

## Finish configuring Zapier

Going back to Zapier, we need to select the type of Action that will occur in xMatters when our Scout Alert triggers. There is only one to choose, *Create Event*, so go with that one and click continue.

The next step is to configure the details of this Create Event. First of all, paste the URL that you got from xMatters into the Web Service URL field. Next, for the Properties field, choose which information from Scout that you want to appear in xMatters. The box on the left corresponds to the fields in xMatters that you want to populate, and the box on the right corresponds to the fields coming from Scout. It is only possible to pull this data from Scout here if you created an Alert earlier like we advised.

![20](https://user-images.githubusercontent.com/43639290/55215035-b4b7c000-523b-11e9-8191-cab4a3433914.png "Configure the Event Template")

Then it would be a good idea to test that the Action works correctly.

![21](https://user-images.githubusercontent.com/43639290/55215036-b4b7c000-523b-11e9-89b5-2d43d179fc7d.png "Test the Action")

Then all that's left to do is to give your Zap a descriptive name and enable it.

![22](https://user-images.githubusercontent.com/43639290/55215037-b5505680-523b-11e9-9c31-3addf32ac561.png "Give your zap a name")

Now everything is set up so that whenever an Alert occurs in Scout which is linked to this Notification Channel, you will see a message in xMatters.

![23](https://user-images.githubusercontent.com/43639290/55215038-b5505680-523b-11e9-9934-921a043b4750.png "The end result")
